<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTmhb514\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTmhb514/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTmhb514.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTmhb514\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTmhb514\appProdProjectContainer([
    'container.build_hash' => 'Tmhb514',
    'container.build_id' => 'c100791a',
    'container.build_time' => 1655989620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTmhb514');
